import type {
  Activity,
  Audience,
  BookingKind,
  DayOfWeek,
  Delivery,
  Goal,
  Language,
  Level,
  PriceUnit,
  Template,
  TimeOfDay,
} from './types';
import { STATIONS } from './metro';

export const CATEGORIES = [
  'Yoga',
  'Languages',
  'Coding',
  'Dance',
  'Cooking',
  'Tennis',
  'Pottery',
  'Theatre',
  'Fitness',
  'Music',
  'Photography',
  'Chess',
  'Swimming',
  'Pilates',
  'Painting',
  'Public Speaking',
] as const;

export const POPULAR = [
  'Yoga',
  'Languages',
  'Tennis',
  'Pottery',
  'Cooking',
  'Dance',
  'Coding',
  'Swimming',
] as const;

export const GOAL_MAP: Record<string, string[]> = {
  Learn: ['Languages', 'Coding', 'Chess', 'Public Speaking'],
  Exercise: ['Yoga', 'Fitness', 'Tennis', 'Swimming', 'Pilates'],
  Create: ['Pottery', 'Painting', 'Photography', 'Music'],
  Relax: ['Yoga', 'Pilates', 'Painting'],
  'Meet People': ['Dance', 'Cooking', 'Theatre'],
  Career: ['Coding', 'Public Speaking', 'Languages'],
  Kids: ['Chess', 'Swimming', 'Theatre', 'Dance'],
};

function covers(slug: string): string[] {
  return [1, 2, 3, 4].map((n) => `/covers/${slug}-${n}.webp`);
}

export const COVER: Record<string, string[]> = {
  Yoga: covers('yoga'),
  Languages: covers('languages'),
  Coding: covers('coding'),
  Dance: covers('dance'),
  Cooking: covers('cooking'),
  Tennis: covers('tennis'),
  Pottery: covers('pottery'),
  Theatre: covers('theatre'),
  Fitness: covers('fitness'),
  Music: covers('music'),
  Photography: covers('photography'),
  Chess: covers('chess'),
  Swimming: covers('swimming'),
  Pilates: covers('pilates'),
  Painting: covers('painting'),
  'Public Speaking': covers('public-speaking'),
};

export const HERO_MOSCOW = '/covers/moscow-hero.webp';

export function coverForCategory(category: string, n = 0): string {
  const list = COVER[category] ?? COVER['Yoga'] ?? [];
  return list[n % Math.max(list.length, 1)] ?? '/covers/yoga-1.webp';
}

function coverFor(category: string, n: number): string {
  const list = COVER[category] ?? COVER['Yoga'] ?? [];
  return list[n % Math.max(list.length, 1)] ?? '/covers/yoga-1.webp';
}

interface Real {
  category: string;
  title: string;
  studio: string;
  host: string;
  bio: string;
  blurb: string;
  long: string;
  goals: Goal[];
  template: Template;
  audience: Audience;
  level: Level;
  language: Language;
  days: DayOfWeek[];
  time: TimeOfDay;
  start: string;
  end: string;
  freq: string;
  price: number;
  unit: PriceUnit;
  stationId?: string;
  venue: string;
  address: string;
  walk?: number;
  seats: number;
  taken?: number;
  featured?: boolean;
  fresh?: boolean;
  pop: number;
  startedDaysAgo: number;
  delivery?: Delivery;
  platform?: string;
  booking?: BookingKind;
  cover?: number;
}

function isoFromToday(offset: number): string {
  const d = new Date();
  d.setDate(d.getDate() + offset);
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${y}-${m}-${day}`;
}

export function activitySlug(title: string, stationId?: string): string {
  const base = title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 48);
  return stationId ? `${base}-${stationId}` : `live-${base}`;
}

function stationOrThrow(id: string) {
  const s = STATIONS.find((x) => x.id === id);
  if (!s) throw new Error(`Unknown station ${id}`);
  return s;
}

const REAL: Real[] = [
  {
    category: 'Yoga',
    title: 'HOLI evening hatha, Malaya Ordynka',
    studio: 'HOLI Yoga & Cafe',
    host: 'HOLI faculty',
    bio: 'HOLI Yoga & Cafe on Malaya Ordynka — a Tretyakovskaya studio with a plant kitchen by Kirill Gubin. Group classes daily 09:00–21:00.',
    blurb: 'Ninety minutes after work. Mats in the room. Trial: any 3 classes for 2 400 ₽.',
    long: 'HOLI Tretyakovskaya is a small central studio, not a nightclub with a gong. Hatha and flow run on a posted timetable; pick a level you can hold. Changing space and the cafe are in the same building. The 3-class intro is 2 400 ₽; a regular drop-in is listed here so you can compare with other rooms.',
    goals: ['Exercise', 'Relax'],
    template: 'Class',
    audience: 'Adults',
    level: 'All Levels',
    language: 'Bilingual',
    days: ['Tuesday', 'Thursday', 'Saturday'],
    time: 'Evening',
    start: '19:00',
    end: '20:15',
    freq: 'Several evenings a week',
    price: 1800,
    unit: 'per session',
    stationId: 'novokuz',
    venue: 'HOLI Yoga Tretyakovskaya',
    address: 'ulitsa Malaya Ordynka, 19',
    walk: 7,
    seats: 16,
    taken: 9,
    featured: true,
    pop: 88,
    startedDaysAgo: 21,
    cover: 0,
  },
  {
    category: 'Yoga',
    title: 'HOLI morning practice, Belorusskaya',
    studio: 'HOLI Yoga & Cafe',
    host: 'HOLI faculty',
    bio: 'HOLI’s second room is in ZhK SLAVA, 1-ya ulitsa Yamskogo Polya — a few minutes from Belorusskaya. Same faculty, same kitchen idea, quieter at 08:00.',
    blurb: 'Before the office. Same HOLI timetable, north of Tverskaya Zastava.',
    long: 'Morning classes in the Belorusskaya studio (ZhK SLAVA). Suitable if you already know a sun salutation and do not want heat. Shoes off at the door. The cafe opens with the first class.',
    goals: ['Exercise', 'Relax'],
    template: 'Class',
    audience: 'Adults',
    level: 'All Levels',
    language: 'Russian',
    days: ['Monday', 'Wednesday', 'Friday'],
    time: 'Morning',
    start: '08:00',
    end: '09:00',
    freq: 'Three times a week',
    price: 1800,
    unit: 'per session',
    stationId: 'belorus',
    venue: 'HOLI Yoga Belorusskaya',
    address: '1-ya ulitsa Yamskogo Polya, 1 k1, ZhK SLAVA',
    walk: 8,
    seats: 14,
    taken: 6,
    pop: 74,
    startedDaysAgo: 18,
    cover: 1,
  },
  {
    category: 'Yoga',
    title: 'Bikram 90 at OYOGA, Lva Tolstogo',
    studio: 'OYOGA.CENTER',
    host: 'Patricia Ratajczak',
    bio: 'Patricia Ratajczak teaches the 90-minute Bikram sequence in OYOGA’s 40° room — Russia’s first Bikram studio, open every day including 31 December.',
    blurb: 'Hot room, set 26 poses. Monday 19:00 is Patricia. Towel required.',
    long: 'OYOGA sits on ulitsa Lva Tolstogo, a short walk from Park Kultury. The Bikram 90 is the house class: heat on, sequence fixed, 90 minutes. Book the slot; the room caps. Showers on site. Unlimited-style months from 8 250 ₽; this listing is the evening class as a drop-in.',
    goals: ['Exercise'],
    template: 'Class',
    audience: 'Adults',
    level: 'Intermediate',
    language: 'Bilingual',
    days: ['Monday', 'Wednesday', 'Saturday'],
    time: 'Evening',
    start: '19:00',
    end: '20:30',
    freq: 'Several evenings a week',
    price: 1500,
    unit: 'per session',
    stationId: 'park-kultury',
    venue: 'OYOGA.CENTER',
    address: 'ulitsa Lva Tolstogo, 23/7s3',
    walk: 6,
    seats: 18,
    taken: 11,
    featured: true,
    pop: 86,
    startedDaysAgo: 12,
    cover: 2,
  },
  {
    category: 'Pilates',
    title: 'Inferno hot pilates, OYOGA',
    studio: 'OYOGA.CENTER',
    host: 'Olga Lenskaya',
    bio: 'Olga Lenskaya and Oksana Shinkaruk run Inferno Hot Pilates in the same 40° room as Bikram. Sixty minutes. Book ahead — the slot is marked по записи.',
    blurb: 'Sixty minutes, heat on. Monday 17:45 with Olga.',
    long: 'Mat work that follows a reformer logic, taught in a hot room. If you have only done pilates in a quiet studio, this is louder and wetter. Grip socks help. OYOGA, Lva Tolstogo, Park Kultury.',
    goals: ['Exercise', 'Relax'],
    template: 'Class',
    audience: 'Adults',
    level: 'All Levels',
    language: 'Russian',
    days: ['Monday', 'Wednesday'],
    time: 'Evening',
    start: '17:45',
    end: '18:45',
    freq: 'Twice weekly',
    price: 1400,
    unit: 'per session',
    stationId: 'park-kultury',
    venue: 'OYOGA.CENTER',
    address: 'ulitsa Lva Tolstogo, 23/7s3',
    walk: 6,
    seats: 12,
    taken: 7,
    pop: 71,
    startedDaysAgo: 9,
    cover: 0,
  },
  {
    category: 'Yoga',
    title: 'Kaula yoga, Milyutinsky lane',
    studio: 'Kaula Yoga School',
    host: 'Kaula instructors',
    bio: 'Kaula has taught in this attic suite since 2006 — four halls, three minutes from Chistye Prudy / Turgenevskaya. Trial 700 ₽ if you have never been.',
    blurb: 'Hatha without the boutique markup. Trial 700 ₽, drop-in 1 400 ₽.',
    long: 'Walk from Chistye Prudy toward Rozhdestvensky Boulevard, then into Milyutinsky pereulok to the red house. The rooms are on the mansard floor: light, extractors, no playlist that fights the asana. Good if you want a neighbourhood school rather than a brand.',
    goals: ['Exercise', 'Relax'],
    template: 'Class',
    audience: 'Adults',
    level: 'Beginner',
    language: 'Russian',
    days: ['Tuesday', 'Thursday', 'Sunday'],
    time: 'Evening',
    start: '19:00',
    end: '20:15',
    freq: 'Several evenings a week',
    price: 1400,
    unit: 'per session',
    stationId: 'chistye',
    venue: 'Kaula Yoga, Milyutinsky 15',
    address: 'Milyutinsky pereulok, 15',
    walk: 4,
    seats: 16,
    taken: 8,
    pop: 79,
    startedDaysAgo: 30,
    cover: 3,
  },
  {
    category: 'Languages',
    title: 'Evening Russian, Ruslanguage on Znamenka',
    studio: 'Ruslanguage School',
    host: 'Ruslanguage faculty',
    bio: 'Ruslanguage has taught Russian to foreigners in Moscow since 1991. Teachers from MSU and the Pushkin Institute. Groups of 3–5. TRKI track if you need the exam.',
    blurb: 'Twice a week after work. 4 900 ₽ a week. Five minutes from Arbatskaya.',
    long: 'Znamenka 13s1, second floor, intercom 15. The evening group is for people who live here and cannot sit in a daytime intensive. Cases in sentences. Homework is short. The published evening rate is 4 900 ₽ per week; this listing is a four-week block.',
    goals: ['Learn'],
    template: 'Program',
    audience: 'Adults',
    level: 'Beginner',
    language: 'English',
    days: ['Tuesday', 'Thursday'],
    time: 'Evening',
    start: '19:00',
    end: '20:30',
    freq: 'Twice weekly',
    price: 19600,
    unit: 'per program',
    stationId: 'arbatskaya',
    venue: 'Ruslanguage School',
    address: 'ulitsa Znamenka, 13s1, 2nd floor',
    walk: 5,
    seats: 5,
    taken: 2,
    featured: true,
    pop: 84,
    startedDaysAgo: 7,
    cover: 0,
  },
  {
    category: 'Languages',
    title: 'English groups on Tverskaya',
    studio: 'Maria English School',
    host: 'Maria Djeroyan',
    bio: 'Maria English School sits on Tverskaya 20, three minutes from the station. Groups from five people, 08:00–22:00, including weekend slots.',
    blurb: 'Spoken English in a room on Tverskaya, not a Zoom tile.',
    long: 'Office 527A, fifth floor, Tverskaya 20/1s1. Morning, evening, and Saturday groups after a placement chat. The school also runs one-to-one and a city-walk format if the group wants it.',
    goals: ['Learn', 'Career'],
    template: 'Program',
    audience: 'Adults',
    level: 'All Levels',
    language: 'English',
    days: ['Monday', 'Wednesday'],
    time: 'Evening',
    start: '19:00',
    end: '20:30',
    freq: 'Twice weekly',
    price: 14400,
    unit: 'per program',
    stationId: 'tverskaya',
    venue: 'Maria English School',
    address: 'Tverskaya ulitsa, 20/1s1, office 527A',
    walk: 3,
    seats: 8,
    taken: 4,
    pop: 77,
    startedDaysAgo: 14,
    cover: 1,
  },
  {
    category: 'Languages',
    title: 'Allada evening English, Strastnoy',
    studio: 'Allada School',
    host: 'Allada instructors',
    bio: 'Allada is a Moscow language network. This listing is the Pushkinskaya / Tverskaya / Chekhovskaya branch on Strastnoy Boulevard.',
    blurb: 'Mini-groups after work. Open daily 09:00–22:00.',
    long: 'Strastnoy Boulevard 6s1, a few minutes from Pushkinskaya. Adult English after a level test. Evening groups are the default for people who work in the centre. Promo trial packs appear on the site; the price here is a normal month of twice-weekly classes.',
    goals: ['Learn', 'Career'],
    template: 'Class',
    audience: 'Adults',
    level: 'Intermediate',
    language: 'Bilingual',
    days: ['Tuesday', 'Thursday'],
    time: 'Evening',
    start: '19:30',
    end: '21:00',
    freq: 'Twice weekly',
    price: 9800,
    unit: 'per month',
    stationId: 'pushkin',
    venue: 'Allada School, Strastnoy',
    address: 'Strastnoy Boulevard, 6s1',
    walk: 4,
    seats: 8,
    taken: 5,
    pop: 69,
    startedDaysAgo: 11,
    cover: 2,
  },
  {
    category: 'Dance',
    title: 'Bachata start, SalsaStudio at Winzavod',
    studio: 'SalsaStudio',
    host: 'SalsaStudio coaches',
    bio: 'SalsaStudio has rooms at Kurskaya (Winzavod), Belorusskaya, and Sokolniki. Beginner bachata at Kurskaya: Monday and Wednesday 20:00–21:00. Drop-in 500 ₽, eight-class month 3 000 ₽.',
    blurb: 'Monday and Wednesday 20:00. No partner required. 500 ₽ once, 3 000 ₽ for eight.',
    long: 'Winzavod, 4th Syromyatnichesky pereulok 1, building 5, entrance 17. Social bachata for people who have not danced. The school also runs salsa and kizomba on the same timetable. Shoes you can turn in; a cloakroom by the hall.',
    goals: ['Meet People', 'Exercise'],
    template: 'Class',
    audience: 'Adults',
    level: 'Beginner',
    language: 'Russian',
    days: ['Monday', 'Wednesday'],
    time: 'Evening',
    start: '20:00',
    end: '21:00',
    freq: 'Twice weekly',
    price: 500,
    unit: 'per session',
    stationId: 'kurskaya',
    venue: 'SalsaStudio at Winzavod',
    address: '4-y Syromyatnichesky pereulok, 1 k5, entrance 17',
    walk: 8,
    seats: 20,
    taken: 12,
    featured: true,
    pop: 90,
    startedDaysAgo: 5,
    cover: 0,
  },
  {
    category: 'Dance',
    title: 'Salsa from zero, SalsaStudio Belorusskaya',
    studio: 'SalsaStudio',
    host: 'SalsaStudio coaches',
    bio: 'The Belorusskaya hall is Dance Options, 2-oy Lesnoy pereulok 10 — courtyard, red basement door. Salsa from zero: Tuesday and Thursday 20:00–21:00.',
    blurb: 'Tuesday/Thursday 20:00. Same 500 ₽ drop-in as the other SalsaStudio rooms.',
    long: 'From Belorusskaya Koltsevaya take the Butyrsky Val exit, then 300 m to 2-oy Lesnoy 10. Walk around the building; the door is painted red. Beginner salsa, lead or follow, no couple required.',
    goals: ['Meet People', 'Exercise'],
    template: 'Class',
    audience: 'Adults',
    level: 'Beginner',
    language: 'Russian',
    days: ['Tuesday', 'Thursday'],
    time: 'Evening',
    start: '20:00',
    end: '21:00',
    freq: 'Twice weekly',
    price: 500,
    unit: 'per session',
    stationId: 'belorus',
    venue: 'SalsaStudio at Dance Options',
    address: '2-oy Lesnoy pereulok, 10',
    walk: 7,
    seats: 18,
    taken: 10,
    pop: 76,
    startedDaysAgo: 4,
    cover: 1,
  },
  {
    category: 'Dance',
    title: 'Friday bachata, Crazy Salsa Taganka',
    studio: 'Crazy Salsa',
    host: 'Crazy Salsa coaches',
    bio: 'Crazy Salsa is a pair-dance school with a Taganka hall at Tovarishchesky pereulok 4s5. Trial from 350 ₽; packs from about 663 ₽ a class.',
    blurb: 'Friday night bachata at Taganka. Partner not required.',
    long: 'Tovarishchesky pereulok 4s5, a few minutes from Taganskaya. The first block is pattern; then you rotate. Water and a cloakroom. Neighbourhood bars are optional and not part of the class.',
    goals: ['Meet People', 'Exercise'],
    template: 'Drop-in',
    audience: 'Adults',
    level: 'Beginner',
    language: 'Russian',
    days: ['Friday', 'Saturday'],
    time: 'Evening',
    start: '20:00',
    end: '21:30',
    freq: 'Weekly',
    price: 1200,
    unit: 'per session',
    stationId: 'taganskaya',
    venue: 'Crazy Salsa Taganka',
    address: 'Tovarishchesky pereulok, 4s5',
    walk: 6,
    seats: 24,
    taken: 14,
    featured: true,
    pop: 91,
    startedDaysAgo: 3,
    cover: 2,
  },
  {
    category: 'Dance',
    title: 'Salsa at Crazy Salsa, Malaya Dmitrovka',
    studio: 'Crazy Salsa',
    host: 'Crazy Salsa coaches',
    bio: 'The Pushkinskaya branch is on Malaya Dmitrovka 5/9 — a few minutes from Pushkinskaya / Tverskaya / Chekhovskaya.',
    blurb: 'Centre-of-town salsa. Same Crazy Salsa method as Taganka.',
    long: 'Malaya Dmitrovka 5/9. Evening salsa for beginners and the next rung. Rotate partners. Street shoes off; dance shoes on.',
    goals: ['Meet People', 'Exercise'],
    template: 'Class',
    audience: 'Adults',
    level: 'Beginner',
    language: 'Russian',
    days: ['Monday', 'Wednesday'],
    time: 'Evening',
    start: '19:30',
    end: '21:00',
    freq: 'Twice weekly',
    price: 1200,
    unit: 'per session',
    stationId: 'pushkin',
    venue: 'Crazy Salsa Pushkinskaya',
    address: 'ulitsa Malaya Dmitrovka, 5/9',
    walk: 5,
    seats: 20,
    taken: 9,
    pop: 73,
    startedDaysAgo: 10,
    cover: 3,
  },
  {
    category: 'Cooking',
    title: 'Ginza masterclass, Danilovsky Market',
    studio: 'Ginza Project Culinary School',
    host: 'Vladimir Bedin',
    bio: 'Chef Vladimir Bedin (Romashka Management, Brasserie Lambic) runs the Ginza Project kitchen on the second floor of Danilovsky Market. Public masterclasses and private hire.',
    blurb: 'Cook in the market kitchen, then eat it. Produce is downstairs.',
    long: 'Mytnaya 74, Danilovsky Market, 2nd floor. A scheduled group masterclass — not the private-hire rate on the studio site (those start at 40 000 ₽ for the room). You cook, you sit, you leave with the recipes. Closed-toe shoes. Dietary notes 48 hours ahead if you can.',
    goals: ['Create', 'Meet People'],
    template: 'Workshop',
    audience: 'Adults',
    level: 'All Levels',
    language: 'Russian',
    days: ['Wednesday', 'Saturday'],
    time: 'Evening',
    start: '18:30',
    end: '21:00',
    freq: 'Weekly',
    price: 5900,
    unit: 'per session',
    stationId: 'dobrynin',
    venue: 'Ginza Culinary School',
    address: 'ulitsa Mytnaya, 74, Danilovsky Market, 2nd floor',
    walk: 8,
    seats: 12,
    taken: 7,
    featured: true,
    pop: 82,
    startedDaysAgo: 2,
    cover: 0,
  },
  {
    category: 'Tennis',
    title: 'Saturday rally clinic, Luzhniki Tennis Palace',
    studio: 'Luzhniki Tennis Palace',
    host: 'Luzhniki academy coaches',
    bio: 'Group clinics on the Luzhniki courts (ulitsa Luzhniki 24) — outdoor in season, bubble when the river wind wins. Nearest metro Vorobyovy Gory.',
    blurb: 'Saturday 09:00. Four on a court. Bring a racquet; balls are there.',
    long: 'A clinic for people who already have a forehand and want it to last a set. Footwork first. In winter the same slot moves under the bubble. Showers in the palace. Court shoes, not runners with a smooth sole.',
    goals: ['Exercise'],
    template: 'Class',
    audience: 'Adults',
    level: 'Intermediate',
    language: 'Russian',
    days: ['Saturday'],
    time: 'Morning',
    start: '09:00',
    end: '10:30',
    freq: 'Weekly',
    price: 4200,
    unit: 'per session',
    stationId: 'vorobyovy',
    venue: 'Luzhniki Tennis Palace',
    address: 'ulitsa Luzhniki, 24s21',
    walk: 12,
    seats: 4,
    taken: 2,
    pop: 70,
    startedDaysAgo: 16,
    cover: 0,
  },
  {
    category: 'Tennis',
    title: 'Evening hitting, CSKA Khodynka',
    studio: 'CSKA courts',
    host: 'CSKA tennis coaches',
    bio: 'Indoor and bubble courts on Khodynka, a short walk from CSKA on the Bolshaya Koltsevaya line.',
    blurb: 'Weeknight clinic, groups of four. After work, before the late booking wave.',
    long: 'Khodynsky Boulevard courts next to CSKA Arena / Megasport. Intermediate rally work. Bring a racquet. Water on the bench.',
    goals: ['Exercise'],
    template: 'Class',
    audience: 'Adults',
    level: 'Intermediate',
    language: 'Russian',
    days: ['Tuesday', 'Thursday'],
    time: 'Evening',
    start: '19:00',
    end: '20:30',
    freq: 'Twice weekly',
    price: 3800,
    unit: 'per session',
    stationId: 'cska',
    venue: 'CSKA / Khodynka courts',
    address: 'Khodynsky Boulevard, 3',
    walk: 6,
    seats: 4,
    taken: 1,
    pop: 66,
    startedDaysAgo: 8,
    cover: 1,
  },
  {
    category: 'Pottery',
    title: 'Wheel throwing at Flacon',
    studio: 'Flacon ceramic workshop',
    host: 'Flacon studio potters',
    bio: 'Drop-in wheel and hand-building sessions run in the Flacon cluster (Bolshaya Novodmitrovskaya 36), a walk from Savyolovskaya. Firing included; pickup on a later visit.',
    blurb: 'Two hours on the wheel. Clay and a firing. Apron on site.',
    long: 'Thursday and Saturday evenings in a Flacon workshop. One lump of clay, glaze later. Hair tied back. The cluster is a former glass factory; the walk from Savyolovskaya is along Novodmitrovskaya.',
    goals: ['Create', 'Relax'],
    template: 'Workshop',
    audience: 'Adults',
    level: 'Beginner',
    language: 'Russian',
    days: ['Thursday', 'Saturday'],
    time: 'Evening',
    start: '19:00',
    end: '21:00',
    freq: 'Weekly',
    price: 3000,
    unit: 'per session',
    stationId: 'savyolov',
    venue: 'Flacon Design Factory',
    address: 'Bolshaya Novodmitrovskaya ulitsa, 36',
    walk: 10,
    seats: 8,
    taken: 5,
    pop: 80,
    startedDaysAgo: 6,
    cover: 0,
  },
  {
    category: 'Pottery',
    title: 'Thursday wheel at Artplay',
    studio: 'Artplay ceramic workshop',
    host: 'Artplay studio potters',
    bio: 'Artplay (Nizhny Susalny / Nizhnyaya Syromyatnicheskaya) holds recurring ceramic workshops in the factory halls near Kurskaya.',
    blurb: 'Clay in a former factory. Firing included, mug in two weeks.',
    long: 'Evening wheel class in the Artplay cluster. Aprons and tools on site. You leave the wet piece; you collect after the kiln. Comfortable shoes — the yards are cobble and rail.',
    goals: ['Create', 'Relax'],
    template: 'Class',
    audience: 'Adults',
    level: 'Beginner',
    language: 'Russian',
    days: ['Thursday'],
    time: 'Evening',
    start: '19:00',
    end: '21:00',
    freq: 'Weekly',
    price: 2900,
    unit: 'per session',
    stationId: 'kurskaya',
    venue: 'Artplay Design Center',
    address: 'Nizhny Susalny pereulok, 5',
    walk: 7,
    seats: 8,
    taken: 4,
    pop: 72,
    startedDaysAgo: 13,
    cover: 1,
  },
  {
    category: 'Theatre',
    title: 'Scene study, Stanislavsky Electrotheatre',
    studio: 'Stanislavsky Electrotheatre',
    host: 'Electrotheatre laboratory',
    bio: 'The Stanislavsky Electrotheatre (Tverskaya 23) runs public laboratories and scene work in the wing next to the main house — not a ticketed show.',
    blurb: 'Sunday afternoon in a black-box room. Contemporary scenes. No parents in the stalls.',
    long: 'A workshop, not a showcase. You work a short scene for a few weeks, then put it down. English and Russian mixed depending on who is in the room. Soft shoes. Tverskaya 23, a few minutes from Tverskaya / Pushkinskaya.',
    goals: ['Meet People', 'Learn'],
    template: 'Workshop',
    audience: 'Adults',
    level: 'All Levels',
    language: 'Bilingual',
    days: ['Sunday'],
    time: 'Afternoon',
    start: '15:00',
    end: '17:30',
    freq: 'Weekly',
    price: 3800,
    unit: 'per session',
    stationId: 'tverskaya',
    venue: 'Stanislavsky Electrotheatre',
    address: 'Tverskaya ulitsa, 23',
    walk: 4,
    seats: 12,
    taken: 6,
    pop: 68,
    startedDaysAgo: 20,
    cover: 0,
  },
  {
    category: 'Fitness',
    title: 'Small-group strength at Chaika',
    studio: 'Chaika sports complex',
    host: 'Chaika floor coaches',
    bio: 'SOK Chaika (Turchaninov pereulok 3s1) is the 1957 pool-and-gym complex by Park Kultury. Group strength and gym floor; showers and sauna in the building. Day visits from about 1 100 ₽ for the pool; gym packs are separate.',
    blurb: 'Barbell, a coach who watches your knee, not a nightclub.',
    long: 'Small-group strength in the Chaika hall. Programming on the board. Deload weeks happen. Showers and the famous outdoor 50 m pool are in the same complex if you add a swim.',
    goals: ['Exercise'],
    template: 'Class',
    audience: 'Adults',
    level: 'Intermediate',
    language: 'Russian',
    days: ['Tuesday', 'Friday'],
    time: 'Evening',
    start: '18:30',
    end: '19:30',
    freq: 'Twice weekly',
    price: 2200,
    unit: 'per session',
    stationId: 'park-kultury',
    venue: 'Chaika sports complex',
    address: 'Turchaninov pereulok, 3s1',
    walk: 8,
    seats: 8,
    taken: 5,
    pop: 75,
    startedDaysAgo: 19,
    cover: 0,
  },
  {
    category: 'Fitness',
    title: 'Encore City evening strength, OKO',
    studio: 'Encore Fitness City',
    host: 'Encore City coaches',
    bio: 'Encore City occupies 3 900 m² in the OKO crystal, 1-y Krasnogvardeysky proezd 21s2 — pool, cycle, combat, and a large functional floor. Moscow City, Delovoy Tsentr.',
    blurb: 'Small-group floor work in OKO after the towers empty.',
    long: 'A booked group slot on the functional floor, not a wander around the machines. Guest and pack rules follow the club; this listing is the evening class as a session. Towel from the desk or bring your own.',
    goals: ['Exercise'],
    template: 'Class',
    audience: 'Adults',
    level: 'Intermediate',
    language: 'Russian',
    days: ['Monday', 'Wednesday'],
    time: 'Evening',
    start: '19:00',
    end: '20:00',
    freq: 'Twice weekly',
    price: 3500,
    unit: 'per session',
    stationId: 'city',
    venue: 'Encore Fitness, OKO',
    address: '1-y Krasnogvardeysky proezd, 21s2, 3rd floor',
    walk: 6,
    seats: 10,
    taken: 6,
    pop: 67,
    startedDaysAgo: 15,
    cover: 1,
  },
  {
    category: 'Music',
    title: 'Acoustic guitar, ArbatGuitar Park Kultury',
    studio: 'ArbatGuitar',
    host: 'ArbatGuitar teachers',
    bio: 'ArbatGuitar teaches acoustic, electric, bass, and ukulele at Zubovsky boulevard 13s1, Park Kultury. Trial individual 1 000 ₽. Popular micro-group: 2–3 people, about 7 500 ₽ for four lessons.',
    blurb: 'Four chords that sound like songs. Micro-group, 60 minutes.',
    long: 'Monday evening in the Park Kultury classroom. You leave able to accompany two songs you actually like. Amps stay quiet. Nobody is forced to perform for the group.',
    goals: ['Create', 'Learn'],
    template: 'Program',
    audience: 'Adults',
    level: 'Beginner',
    language: 'Russian',
    days: ['Monday'],
    time: 'Evening',
    start: '19:00',
    end: '20:00',
    freq: 'Weekly',
    price: 7500,
    unit: 'per month',
    stationId: 'park-kultury',
    venue: 'ArbatGuitar',
    address: 'Zubovsky boulevard, 13s1',
    walk: 5,
    seats: 3,
    taken: 1,
    pop: 64,
    startedDaysAgo: 17,
    cover: 0,
  },
  {
    category: 'Photography',
    title: 'Photoplay: foundations, Kalanchevskaya',
    studio: 'Photoplay',
    host: 'Photoplay faculty',
    bio: 'Photoplay (opened 2005) is a photography school with ten Profoto studios 300 m from Krasnye Vorota — Kalanchevskaya 17, 6th floor. The 12-session foundations course is 35 000 ₽, six weeks, evening group.',
    blurb: 'Twelve evenings. Camera or a current phone for the first weeks.',
    long: 'Kalanchevskaya 17, sixth floor. Walk from Komsomolskaya along the three-station knot; Krasnye Vorota is even closer. Critique in the room, not a WhatsApp dump. One session of the twelve is online. 10% off studio rental while you are enrolled.',
    goals: ['Create'],
    template: 'Program',
    audience: 'Adults',
    level: 'Beginner',
    language: 'Russian',
    days: ['Tuesday', 'Thursday'],
    time: 'Evening',
    start: '19:00',
    end: '22:00',
    freq: 'Twice weekly',
    price: 35000,
    unit: 'per program',
    stationId: 'komsomol',
    venue: 'Photoplay',
    address: 'Kalanchevskaya ulitsa, 17, 6th floor',
    walk: 8,
    seats: 12,
    taken: 7,
    featured: true,
    pop: 81,
    startedDaysAgo: 1,
    fresh: true,
    cover: 0,
  },
  {
    category: 'Photography',
    title: 'Saturday light walk from Chistye Prudy',
    studio: 'Photoplay outdoor',
    host: 'Photoplay instructors',
    bio: 'A walking assignment run with Photoplay’s beginner track: one boulevard, one hour of light, critique the following week in the Kalanchevskaya studios.',
    blurb: 'How to stop taking the same dome. Meet at the station.',
    long: 'Start at Chistye Prudy pavilion, end when the light dies. One brief: a single street. Phones allowed. The indoor critique is at Photoplay the next week if you are on the foundations course; this walk can be booked on its own.',
    goals: ['Create'],
    template: 'Workshop',
    audience: 'Adults',
    level: 'All Levels',
    language: 'Russian',
    days: ['Saturday'],
    time: 'Afternoon',
    start: '16:00',
    end: '18:30',
    freq: 'Weekly',
    price: 3200,
    unit: 'per session',
    stationId: 'chistye',
    venue: 'Chistye Prudy pavilion',
    address: 'Chistoprudny Boulevard, 12',
    walk: 2,
    seats: 10,
    taken: 4,
    pop: 63,
    startedDaysAgo: 0,
    fresh: true,
    cover: 1,
  },
  {
    category: 'Pilates',
    title: 'Morning pilates, Chaika hall',
    studio: 'Chaika sports complex',
    host: 'Chaika group-ex instructors',
    bio: 'Chaika’s timetable includes pilates and stretching in the group hall at Turchaninov 3s1, Park Kultury. The complex opens from 07:00 on weekdays.',
    blurb: 'Forty-five minutes before the office. Socks with grip if you have them.',
    long: 'Morning mat pilates in a sports-complex room, not a boutique reformer loft. Showers in the building. Combine with a lane at the 50 m pool if you have time.',
    goals: ['Exercise', 'Relax'],
    template: 'Class',
    audience: 'Adults',
    level: 'All Levels',
    language: 'Russian',
    days: ['Wednesday', 'Saturday'],
    time: 'Morning',
    start: '07:45',
    end: '08:30',
    freq: 'Twice weekly',
    price: 1600,
    unit: 'per session',
    stationId: 'park-kultury',
    venue: 'Chaika sports complex',
    address: 'Turchaninov pereulok, 3s1',
    walk: 8,
    seats: 14,
    taken: 8,
    pop: 61,
    startedDaysAgo: 22,
    cover: 1,
  },
  {
    category: 'Swimming',
    title: 'Lane swim, Chaika 50 m',
    studio: 'Chaika sports complex',
    host: 'Chaika deck staff',
    bio: 'The open-air 50 m Chaika pool (18 lanes) at Turchaninov 3s1. Day visit about 1 100 ₽; monthly from about 10 000 ₽. Open ~07:00–22:45 weekdays, shorter on Sunday.',
    blurb: 'Fifty metres, heat in the water, Park Kultury. Medical slip rules apply.',
    long: 'A booked lane session, not a kids group. Caps on. The pool is a 1957 festival building; in winter it still runs. Bring a certificate if the desk asks — Chaika is strict about health papers.',
    goals: ['Exercise'],
    template: 'Drop-in',
    audience: 'Adults',
    level: 'All Levels',
    language: 'Russian',
    days: ['Monday', 'Wednesday', 'Saturday'],
    time: 'Evening',
    start: '19:00',
    end: '20:00',
    freq: 'Several evenings a week',
    price: 1100,
    unit: 'per session',
    stationId: 'park-kultury',
    venue: 'Chaika pool',
    address: 'Turchaninov pereulok, 3s1',
    walk: 8,
    seats: 8,
    taken: 3,
    featured: true,
    pop: 85,
    startedDaysAgo: 25,
    cover: 0,
  },
  {
    category: 'Public Speaking',
    title: 'Moscow Toastbusters, Krasnaya Presnya Park',
    studio: 'Moscow Toastbusters',
    host: 'Toastbusters officers',
    bio: 'Toastmasters club 02539011. Meets Wednesday every other week at 19:00 in the music salon, Krasnaya Presnya Park (left arch), Mantulinskaya 5s1. Guests welcome; online attendance allowed.',
    blurb: 'English-language club. First visit as a guest; then dues if you join.',
    long: 'A structured meeting: speeches, evaluations, table topics. Not a paid oratory school — a Toastmasters club that has met since 2012. Nearest listed metro for this map is Krasnopresnenskaya; the park is also a walk from Ulitsa 1905 Goda. Guest visits are free; the price here is a typical monthly club+international dues once you join.',
    goals: ['Career', 'Learn'],
    template: 'Class',
    audience: 'Adults',
    level: 'All Levels',
    language: 'English',
    days: ['Wednesday'],
    time: 'Evening',
    start: '19:00',
    end: '21:00',
    freq: 'Every other week',
    price: 2500,
    unit: 'per month',
    stationId: 'krasno',
    venue: 'Krasnaya Presnya Park, music salon',
    address: 'Mantulinskaya ulitsa, 5s1',
    walk: 12,
    seats: 20,
    taken: 11,
    pop: 58,
    startedDaysAgo: 28,
    cover: 0,
  },
  {
    category: 'Chess',
    title: 'Chess club, Sokolniki gymnasium',
    studio: 'ChessHoliday — Podrastayushchee Pokolenie',
    host: 'Roman Sevostyanov',
    bio: 'Roman Sevostyanov (KMS, 15+ years coaching) runs the school at the European Gymnasium, Sokolnichesky Val 28. Published groups: Tuesday and Thursday 18:00–20:00. 4 500 ₽ for four sessions, 6 000 ₽ for eight, 1 250 ₽ drop-in.',
    blurb: 'Slow games, no timers in the first month. Parent waits in the corridor.',
    long: 'Boards stay on the table. The room is a school hall, not a tournament hall, until a child asks. Walk from Sokolniki metro along the val. Ages 7–12.',
    goals: ['Kids', 'Learn'],
    template: 'Class',
    audience: 'Children',
    level: 'Beginner',
    language: 'Russian',
    days: ['Tuesday', 'Thursday'],
    time: 'Evening',
    start: '18:00',
    end: '20:00',
    freq: 'Twice weekly',
    price: 1250,
    unit: 'per session',
    stationId: 'sokolniki',
    venue: 'European Gymnasium, Sokolniki',
    address: 'Sokolnichesky Val, 28',
    walk: 8,
    seats: 12,
    taken: 7,
    pop: 78,
    startedDaysAgo: 24,
    cover: 0,
  },
  {
    category: 'Swimming',
    title: 'Kids swim, School No.1 Sokolniki',
    studio: 'School of Swimming No. 1',
    host: 'School No.1 instructors',
    bio: 'Warm-water teaching pool at Bolshaya Tikhonovskaya 18s1, Sokolniki. Groups for 3–6 and 7–12, including children who cannot swim yet. Water about 32°C.',
    blurb: 'Small groups, after school. Parents in the gallery, not on the deck.',
    long: 'Two pools in the complex (infant and preschool/school). Caps can be borrowed once. Bring a certificate if the desk requires it. Twice weekly is the usual pack.',
    goals: ['Kids', 'Exercise'],
    template: 'Program',
    audience: 'Children',
    level: 'Beginner',
    language: 'Russian',
    days: ['Tuesday', 'Thursday'],
    time: 'Afternoon',
    start: '16:30',
    end: '17:20',
    freq: 'Twice weekly',
    price: 12000,
    unit: 'per month',
    stationId: 'sokolniki',
    venue: 'Pool Sokolniki, Bolshaya Tikhonovskaya',
    address: 'Bolshaya Tikhonovskaya ulitsa, 18s1',
    walk: 10,
    seats: 6,
    taken: 4,
    pop: 83,
    startedDaysAgo: 27,
    cover: 1,
  },
  {
    category: 'Dance',
    title: 'Kids contemporary, Sokolniki park hall',
    studio: 'Sokolniki park studios',
    host: 'Park hall teachers',
    bio: 'After-school contemporary in the Sokolniki park sports hall — Sokolnichesky Val, a walk from the metro. Bare feet, one water break, no recital costumes in the first term.',
    blurb: 'Wednesday after school. Ages 8–12. Changing room on site.',
    long: 'Floor work and rhythm. The kind of class they ask to repeat. Parents collect from the corridor, not from the stage.',
    goals: ['Kids', 'Create'],
    template: 'Class',
    audience: 'Children',
    level: 'Beginner',
    language: 'Russian',
    days: ['Wednesday'],
    time: 'Afternoon',
    start: '16:00',
    end: '17:00',
    freq: 'Weekly',
    price: 7200,
    unit: 'per month',
    stationId: 'sokolniki',
    venue: 'Sokolniki Park sports hall',
    address: 'Sokolnichesky Val, 1',
    walk: 6,
    seats: 14,
    taken: 8,
    pop: 60,
    startedDaysAgo: 15,
    cover: 0,
  },
  {
    category: 'Theatre',
    title: 'After-school drama, Taganka studios',
    studio: 'Taganka Theatre studios',
    host: 'Taganka studio pedagogues',
    bio: 'Children’s drama groups in the Taganka education rooms off Taganskaya ploshchad — improvisation and short plays, not a ticketed evening.',
    blurb: 'Friday groups of twelve. Collect from the corridor at 17:30.',
    long: 'Russian-language room with some English games. One trunk of costumes. Parents do not sit in after the first week.',
    goals: ['Kids', 'Meet People'],
    template: 'Program',
    audience: 'Children',
    level: 'All Levels',
    language: 'Russian',
    days: ['Friday'],
    time: 'Afternoon',
    start: '16:00',
    end: '17:30',
    freq: 'Weekly',
    price: 6900,
    unit: 'per month',
    stationId: 'taganskaya',
    venue: 'Taganka Theatre studios',
    address: 'Taganskaya ploshchad, 12',
    walk: 5,
    seats: 12,
    taken: 7,
    pop: 62,
    startedDaysAgo: 18,
    cover: 1,
  },
  {
    category: 'Coding',
    title: 'Python + AI, KIBERone Sokolniki',
    studio: 'KIBERone Sokolniki',
    host: 'KIBERone mentors',
    bio: 'KIBERone’s Sokolniki cyber-school: Python module for ages 10–15, 11 lessons × 2 hours, first digital project with an AI helper in the loop.',
    blurb: 'Saturday lab. Laptops in the room. They leave with a small program they can show.',
    long: 'Variables, loops, debugging, then a tiny project. Snacks are not sold in the lab. Parents wait outside after drop-off.',
    goals: ['Kids', 'Learn'],
    template: 'Camp',
    audience: 'Children',
    level: 'Beginner',
    language: 'Russian',
    days: ['Saturday'],
    time: 'Morning',
    start: '10:00',
    end: '12:00',
    freq: 'Weekly',
    price: 5900,
    unit: 'per month',
    stationId: 'sokolniki',
    venue: 'KIBERone Sokolniki',
    address: 'Sokolniki, KIBERone campus (moscow-sok.kiber-one.com)',
    walk: 9,
    seats: 10,
    taken: 6,
    pop: 71,
    startedDaysAgo: 9,
    cover: 0,
  },
  {
    category: 'Painting',
    title: 'Kids gouache, Lab-of-art Winzavod',
    studio: 'Lab-of-art',
    host: 'Lab-of-art studio artists',
    bio: 'Lab-of-art is a Winzavod resident (4th Syromyatnichesky 1/8, Kurskaya / Chkalovskaya). Group workshops for children and adults; everyone leaves with a painting.',
    blurb: 'Sunday morning. Big paper, stained aprons, work that goes home wet.',
    long: 'Ages 6–10. Non-toxic paint. Parents do not sit in unless the child is new that week. Pickup at the studio door, not from the easel.',
    goals: ['Kids', 'Create'],
    template: 'Class',
    audience: 'Children',
    level: 'Beginner',
    language: 'Russian',
    days: ['Sunday'],
    time: 'Morning',
    start: '11:00',
    end: '12:30',
    freq: 'Weekly',
    price: 2500,
    unit: 'per session',
    stationId: 'kurskaya',
    venue: 'Lab-of-art at Winzavod',
    address: '4-y Syromyatnichesky pereulok, 1/8',
    walk: 9,
    seats: 10,
    taken: 5,
    pop: 74,
    startedDaysAgo: 11,
    cover: 0,
  },
  {
    category: 'Tennis',
    title: 'Mini-tennis, red balls, Luzhniki',
    studio: 'Luzhniki Tennis Palace',
    host: 'Luzhniki junior coaches',
    bio: 'Short-court mini-tennis for 6–9s at Luzhniki 24. Indoor in winter. Racquets in 21–23 inch if needed.',
    blurb: 'Saturday afternoon. Plenty of rallies. One adult on the bench.',
    long: 'Red balls, short court. The point is rallying, not a lecture on grips. Water break. Collect from the fence, not from the far baseline.',
    goals: ['Kids', 'Exercise'],
    template: 'Class',
    audience: 'Children',
    level: 'Beginner',
    language: 'Russian',
    days: ['Saturday'],
    time: 'Afternoon',
    start: '13:00',
    end: '14:00',
    freq: 'Weekly',
    price: 3400,
    unit: 'per session',
    stationId: 'vorobyovy',
    venue: 'Luzhniki Tennis Palace',
    address: 'ulitsa Luzhniki, 24s21',
    walk: 12,
    seats: 6,
    taken: 3,
    pop: 65,
    startedDaysAgo: 14,
    cover: 2,
  },
  {
    category: 'Pottery',
    title: 'Clay club, Lab-of-art kids',
    studio: 'Lab-of-art',
    host: 'Lab-of-art studio artists',
    bio: 'The same Winzavod workshop runs clay sessions for 7–11: pinch pots and animals, firing included, pickup the following week.',
    blurb: 'Saturday clay. Everything labelled. Hair ties recommended.',
    long: 'Dust managed; glaze food-safe on cups. Parents wait in the corridor. Winzavod, 4th Syromyatnichesky 1/8.',
    goals: ['Kids', 'Create'],
    template: 'Workshop',
    audience: 'Children',
    level: 'Beginner',
    language: 'Russian',
    days: ['Saturday'],
    time: 'Afternoon',
    start: '15:00',
    end: '16:30',
    freq: 'Weekly',
    price: 2500,
    unit: 'per session',
    stationId: 'kurskaya',
    venue: 'Lab-of-art at Winzavod',
    address: '4-y Syromyatnichesky pereulok, 1/8',
    walk: 9,
    seats: 8,
    taken: 4,
    pop: 69,
    startedDaysAgo: 8,
    cover: 2,
  },
  {
    category: 'Languages',
    title: 'Kids English, Possumus Sokolniki',
    studio: 'Possumus',
    host: 'Possumus teachers',
    bio: 'Possumus is a Sokolniki English and Spanish school at Staroslobodskaya 16/17, office 6. Mini-groups of 2–5, children from age 4, Cambridge/Oxford materials for school-age.',
    blurb: 'Picture books and spoken games. Max five children. Cloakroom for January.',
    long: 'Twice weekly after school. A parent stays for the first two sessions if the child is new. 90–100% of the older-kids hour is in English once they have settled.',
    goals: ['Kids', 'Learn'],
    template: 'Program',
    audience: 'Children',
    level: 'Beginner',
    language: 'English',
    days: ['Monday', 'Wednesday'],
    time: 'Afternoon',
    start: '16:30',
    end: '17:30',
    freq: 'Twice weekly',
    price: 9800,
    unit: 'per month',
    stationId: 'sokolniki',
    venue: 'Possumus',
    address: 'Staroslobodskaya ulitsa, 16/17, office 6',
    walk: 7,
    seats: 5,
    taken: 3,
    pop: 72,
    startedDaysAgo: 20,
    cover: 3,
  },
  {
    category: 'Swimming',
    title: 'Kids lanes, Chaika',
    studio: 'Chaika sports complex',
    host: 'Chaika swim coaches',
    bio: 'Chaika runs children’s fitness and swim groups in the same Turchaninov complex as the 50 m pool. Parents in the gallery.',
    blurb: 'After-school swim. Caps on. Four to a coach when the group is small.',
    long: 'Warm-up, drill, play. No races until they ask. The outdoor pool is an event; the kids groups use the teaching water the desk assigns.',
    goals: ['Kids', 'Exercise'],
    template: 'Program',
    audience: 'Children',
    level: 'Beginner',
    language: 'Russian',
    days: ['Tuesday', 'Thursday'],
    time: 'Afternoon',
    start: '16:00',
    end: '16:50',
    freq: 'Twice weekly',
    price: 14000,
    unit: 'per month',
    stationId: 'park-kultury',
    venue: 'Chaika pool',
    address: 'Turchaninov pereulok, 3s1',
    walk: 8,
    seats: 6,
    taken: 4,
    pop: 77,
    startedDaysAgo: 23,
    cover: 2,
  },
  {
    category: 'Public Speaking',
    title: 'Boardroom voice, closed door — City',
    studio: 'Moscow City training rooms',
    host: 'Independent facilitators',
    bio: 'A half-day workshop hired into a Moscow City meeting room (IQ-Quarter / Federation) — recorded rounds, then live. Russian or English track booked in advance. NDA on request.',
    blurb: 'For teams that present too fast and apologise too often.',
    long: 'Not a public drop-in. You book the room and the facilitator. Invoice in RUB, VAT as agreed. 10:00–13:00 typical.',
    goals: ['Career'],
    template: 'Corporate',
    audience: 'Corporate',
    level: 'All Levels',
    language: 'English',
    days: ['Tuesday'],
    time: 'Morning',
    start: '10:00',
    end: '13:00',
    freq: 'By arrangement',
    price: 180000,
    unit: 'total program',
    stationId: 'city',
    venue: 'IQ-Quarter hall',
    address: 'Presnenskaya naberezhnaya, 12',
    walk: 5,
    seats: 12,
    taken: 0,
    pop: 54,
    startedDaysAgo: 4,
    booking: 'Request Spot',
    cover: 1,
  },
  {
    category: 'Cooking',
    title: 'Team kitchen, Ginza Danilovsky',
    studio: 'Ginza Project Culinary School',
    host: 'Vladimir Bedin',
    bio: 'Private hire of the Ginza kitchen at Danilovsky Market. Weekday 15:00 masterclass hire is published from 80 000 ₽ + 10% service; weekends higher.',
    blurb: 'Twelve people, one table, a menu that has to land together.',
    long: 'Offsite cooking in the market studio. Dietary constraints 72 hours ahead. You eat standing or seated depending on the set. Invoice in RUB. This is the Friday afternoon team slot, not the public masterclass.',
    goals: ['Meet People'],
    template: 'Corporate',
    audience: 'Corporate',
    level: 'All Levels',
    language: 'Russian',
    days: ['Friday'],
    time: 'Afternoon',
    start: '15:00',
    end: '18:00',
    freq: 'By arrangement',
    price: 80000,
    unit: 'total program',
    stationId: 'dobrynin',
    venue: 'Ginza Culinary School',
    address: 'ulitsa Mytnaya, 74, Danilovsky Market, 2nd floor',
    walk: 8,
    seats: 12,
    taken: 0,
    pop: 70,
    startedDaysAgo: 6,
    booking: 'Request Spot',
    cover: 1,
  },
  {
    category: 'Yoga',
    title: 'Office reset, HOLI or on-site',
    studio: 'HOLI Yoga',
    host: 'HOLI faculty',
    bio: 'HOLI books private morning groups in the Tretyakovskaya or Belorusskaya rooms, or sends a teacher to a nearby office. Forty minutes. Chairs allowed.',
    blurb: 'No lycra requirement. Can run in a meeting room if the floor is decent.',
    long: 'Breath, hips, neck. Mixed mobility. Mats can be delivered to Garden Ring and City offices. Weekly retainer listed as a month.',
    goals: ['Relax', 'Exercise'],
    template: 'Corporate',
    audience: 'Corporate',
    level: 'All Levels',
    language: 'Bilingual',
    days: ['Wednesday'],
    time: 'Morning',
    start: '08:30',
    end: '09:15',
    freq: 'Weekly',
    price: 42000,
    unit: 'per month',
    stationId: 'novokuz',
    venue: 'HOLI Yoga Tretyakovskaya',
    address: 'ulitsa Malaya Ordynka, 19',
    walk: 7,
    seats: 16,
    taken: 0,
    pop: 59,
    startedDaysAgo: 10,
    booking: 'Request Spot',
    cover: 1,
  },
  {
    category: 'Theatre',
    title: 'Improvisation for teams, Taganka',
    studio: 'Taganka Theatre studios',
    host: 'Taganka facilitators',
    bio: 'Three-hour listening drills in a Taganka rehearsal room. No trust falls. English or Russian.',
    blurb: 'Status, timing, saying yes — not a comedy club.',
    long: 'Groups of 8–16. The work is attention, not performance. Invoice as a single hire.',
    goals: ['Meet People', 'Career'],
    template: 'Corporate',
    audience: 'Corporate',
    level: 'All Levels',
    language: 'Bilingual',
    days: ['Monday'],
    time: 'Afternoon',
    start: '15:00',
    end: '18:00',
    freq: 'By arrangement',
    price: 110000,
    unit: 'total program',
    stationId: 'taganskaya',
    venue: 'Taganka Theatre studios',
    address: 'Taganskaya ploshchad, 12',
    walk: 5,
    seats: 16,
    taken: 0,
    pop: 55,
    startedDaysAgo: 12,
    booking: 'Request Spot',
    cover: 2,
  },
  {
    category: 'Photography',
    title: 'Neighbourhood brand walk, Photoplay',
    studio: 'Photoplay',
    host: 'Photoplay commercial faculty',
    bio: 'A guided stills walk with Photoplay instructors — people at work, materials, winter light — then files in a shared folder within five days. Model releases if faces are central.',
    blurb: 'Images a company can use, not stock of the Kremlin.',
    long: 'Meet at Komsomolskaya / Kalanchevskaya. Brief agreed 48 hours ahead. Deliverables in a folder, not Instagram dumps.',
    goals: ['Create', 'Career'],
    template: 'Corporate',
    audience: 'Corporate',
    level: 'All Levels',
    language: 'Russian',
    days: ['Thursday'],
    time: 'Afternoon',
    start: '14:00',
    end: '17:00',
    freq: 'By arrangement',
    price: 74000,
    unit: 'total program',
    stationId: 'komsomol',
    venue: 'Photoplay',
    address: 'Kalanchevskaya ulitsa, 17, 6th floor',
    walk: 8,
    seats: 8,
    taken: 0,
    pop: 52,
    startedDaysAgo: 3,
    booking: 'Request Spot',
    cover: 2,
  },
  {
    category: 'Languages',
    title: 'Live Russian on Zoom, Ruslanguage',
    studio: 'Ruslanguage School',
    host: 'Ruslanguage faculty',
    bio: 'Same evening curriculum as Znamenka, on a live call. Camera on. Moscow time. Groups stay small.',
    blurb: 'For people who cannot cross the city twice a week.',
    long: 'TRKI-aware teacher. Eight on the call at most. Homework in a shared folder. No commute.',
    goals: ['Learn'],
    template: 'Class',
    audience: 'Adults',
    level: 'Beginner',
    language: 'English',
    days: ['Tuesday', 'Thursday'],
    time: 'Evening',
    start: '19:30',
    end: '21:00',
    freq: 'Twice weekly',
    price: 14200,
    unit: 'per program',
    venue: 'Ruslanguage live',
    address: 'Zoom, Moscow time',
    seats: 8,
    taken: 3,
    pop: 73,
    startedDaysAgo: 10,
    delivery: 'Live Online',
    platform: 'Zoom',
    cover: 3,
  },
  {
    category: 'Yoga',
    title: 'OYOGA morning hatha, live',
    studio: 'OYOGA.CENTER',
    host: 'OYOGA faculty',
    bio: 'A 55-minute live class broadcast from the Lva Tolstogo room. The teacher can see you. Not a recording.',
    blurb: 'Moscow 07:30. A mat and a quiet floor are enough.',
    long: 'Hatha without the 40° heat. English cues available on some mornings. Camera on.',
    goals: ['Exercise', 'Relax'],
    template: 'Class',
    audience: 'Adults',
    level: 'All Levels',
    language: 'Bilingual',
    days: ['Monday', 'Wednesday', 'Friday'],
    time: 'Morning',
    start: '07:30',
    end: '08:25',
    freq: 'Three times a week',
    price: 6200,
    unit: 'per month',
    venue: 'OYOGA live from Khamovniki',
    address: 'Google Meet, Moscow time',
    seats: 12,
    taken: 5,
    pop: 66,
    startedDaysAgo: 8,
    delivery: 'Live Online',
    platform: 'Google Meet',
    cover: 3,
  },
  {
    category: 'Coding',
    title: 'Python live cohort, Yandex Practicum',
    studio: 'Yandex Practicum',
    host: 'Practicum mentors',
    bio: 'Yandex Practicum’s Python track is a live online cohort with code review and standups on Moscow time — the same arc as the full-time profession path, evenings.',
    blurb: 'Evenings on the Practicum platform. Pair work in breakouts.',
    long: 'For analysts and operators who are tired of waiting on data teams. Pandas, messy tables, a report you already need at work. No recordings of your screen without consent.',
    goals: ['Learn', 'Career'],
    template: 'Program',
    audience: 'Adults',
    level: 'Beginner',
    language: 'Russian',
    days: ['Monday', 'Thursday'],
    time: 'Evening',
    start: '19:00',
    end: '21:00',
    freq: 'Twice weekly',
    price: 36000,
    unit: 'per program',
    venue: 'Yandex Practicum',
    address: 'Zoom, Moscow time',
    seats: 16,
    taken: 9,
    pop: 80,
    startedDaysAgo: 5,
    delivery: 'Live Online',
    platform: 'Zoom',
    cover: 1,
  },
  {
    category: 'Public Speaking',
    title: 'Camera presence for hybrid teams',
    studio: 'Independent facilitators',
    host: 'Workshop lead',
    bio: 'Four live sessions on how to stop presenting to your own thumbnail. Corporate invoices accepted.',
    blurb: 'You present, you get notes, you present again.',
    long: 'Morning slot so APAC and Europe overlap is not required — this is MSK 10:00. Recorded rounds stay in the company folder.',
    goals: ['Career'],
    template: 'Workshop',
    audience: 'Corporate',
    level: 'All Levels',
    language: 'English',
    days: ['Wednesday'],
    time: 'Morning',
    start: '10:00',
    end: '12:00',
    freq: 'Weekly',
    price: 28000,
    unit: 'per program',
    venue: 'Live workshop',
    address: 'Google Meet, Moscow time',
    seats: 10,
    taken: 2,
    pop: 50,
    startedDaysAgo: 7,
    delivery: 'Live Online',
    platform: 'Google Meet',
    booking: 'Request Spot',
    cover: 2,
  },
  {
    category: 'Languages',
    title: 'Kids’ English stories, live',
    studio: 'Possumus',
    host: 'Possumus teachers',
    bio: 'The Sokolniki school’s live after-school hour for 6–9s who cannot cross town. Picture books on Zoom. Max six. A parent in the room for the first two sessions.',
    blurb: 'Camera required. Moscow afternoons.',
    long: 'Same spoken-first method as the Staroslobodskaya room. No open chat with other children.',
    goals: ['Kids', 'Learn'],
    template: 'Class',
    audience: 'Children',
    level: 'Beginner',
    language: 'English',
    days: ['Monday', 'Wednesday'],
    time: 'Afternoon',
    start: '16:30',
    end: '17:20',
    freq: 'Twice weekly',
    price: 8900,
    unit: 'per program',
    venue: 'Possumus live',
    address: 'Zoom, Moscow time',
    seats: 6,
    taken: 2,
    pop: 64,
    startedDaysAgo: 12,
    delivery: 'Live Online',
    platform: 'Zoom',
    cover: 0,
  },
  {
    category: 'Chess',
    title: 'Online chess club, ChessHoliday',
    studio: 'ChessHoliday',
    host: 'Roman Sevostyanov',
    bio: 'The Sokolniki school also runs an online track: Lichess plus the same coach. Saturday mornings MSK. Ages 7–12.',
    blurb: 'Boards on the screen. No open chat with other children.',
    long: 'Same pedagogy as Sokolnichesky Val 28, without the walk. Parent nearby, not in the call.',
    goals: ['Kids', 'Learn'],
    template: 'Class',
    audience: 'Children',
    level: 'Beginner',
    language: 'Russian',
    days: ['Saturday'],
    time: 'Morning',
    start: '11:00',
    end: '12:00',
    freq: 'Weekly',
    price: 4800,
    unit: 'per month',
    venue: 'ChessHoliday online',
    address: 'Google Meet, Moscow time',
    seats: 10,
    taken: 4,
    pop: 61,
    startedDaysAgo: 16,
    delivery: 'Live Online',
    platform: 'Google Meet',
    cover: 1,
  },
  {
    category: 'Dance',
    title: 'Salsa from zero, SalsaStudio Sokolniki',
    studio: 'SalsaStudio',
    host: 'SalsaStudio coaches',
    bio: 'Salsa start at the Sokolniki hall: Monday and Wednesday 19:30–21:30. Same 500 ₽ drop-in as Kurskaya and Belorusskaya.',
    blurb: 'North-east of the Garden Ring. Beginner salsa, no couple required.',
    long: 'A longer slot than the centre rooms — two hours. Water, cloakroom, street shoes off.',
    goals: ['Meet People', 'Exercise'],
    template: 'Class',
    audience: 'Adults',
    level: 'Beginner',
    language: 'Russian',
    days: ['Monday', 'Wednesday'],
    time: 'Evening',
    start: '19:30',
    end: '21:30',
    freq: 'Twice weekly',
    price: 500,
    unit: 'per session',
    stationId: 'sokolniki',
    venue: 'SalsaStudio Sokolniki',
    address: 'Sokolnicheskaya ploshchad, 7',
    walk: 5,
    seats: 18,
    taken: 8,
    pop: 68,
    startedDaysAgo: 6,
    cover: 0,
  },
  {
    category: 'Cooking',
    title: 'Saturday market kitchen, Ginza',
    studio: 'Ginza Project Culinary School',
    host: 'Vladimir Bedin',
    bio: 'Weekend public masterclass in the same Danilovsky kitchen. Saturday evening is the busy slot — book ahead.',
    blurb: 'Khachapuri or whatever is on the week’s menu. You eat what you make.',
    long: 'Mytnaya 74, 2nd floor. Weekend groups fill faster than Wednesday. Recipes with Russian names intact.',
    goals: ['Create', 'Meet People'],
    template: 'Workshop',
    audience: 'Adults',
    level: 'All Levels',
    language: 'Russian',
    days: ['Saturday'],
    time: 'Evening',
    start: '18:00',
    end: '21:00',
    freq: 'Weekly',
    price: 6500,
    unit: 'per session',
    stationId: 'dobrynin',
    venue: 'Ginza Culinary School',
    address: 'ulitsa Mytnaya, 74, Danilovsky Market, 2nd floor',
    walk: 8,
    seats: 12,
    taken: 8,
    pop: 79,
    startedDaysAgo: 0,
    fresh: true,
    cover: 2,
  },
];

function toActivity(row: Real, index: number): Activity {
  const online = row.delivery === 'Live Online';
  const station = row.stationId ? stationOrThrow(row.stationId) : undefined;
  const seats = row.seats;
  const taken = Math.min(seats - (row.audience === 'Corporate' ? seats : 1), row.taken ?? 0);
  const walk = row.walk;
  const start = isoFromToday(-row.startedDaysAgo);

  return {
    id: activitySlug(row.title, row.stationId),
    title: row.title,
    category: row.category,
    audience: row.audience,
    template: row.template,
    startDate: start,
    frequency: row.freq,
    weekdays: row.days,
    startTime: row.start,
    endTime: row.end,
    duration: `${row.start}–${row.end}`,
    schedule: {
      days: row.days,
      timeOfDay: [row.time],
      timeRange: `${row.start}–${row.end}`,
    },
    ...(station
      ? {
          metroLineId: station.lineId,
          metroLineName: station.lineName,
          metroLineColor: station.lineColor,
          metroStationId: station.id,
          metroStationName: station.name,
          walkMinutes: walk,
          address: row.address,
          district: station.district,
          venue: row.venue,
        }
      : {
          address: row.address,
          venue: row.venue,
        }),
    price: row.price,
    priceUnit: row.unit,
    currency: '₽',
    level: row.level,
    language: row.language,
    shortDescription: online
      ? row.blurb
      : `${row.blurb} ${walk ?? 0} min walk from ${station?.name}.`,
    fullDescription: online
      ? `${row.long} Delivered live. Moscow time (MSK). No commute.`
      : `${row.long} ${row.venue}, ${row.address}. Nearest metro: ${station?.name} (${station?.nameRu}), ${station?.lineName} line. ${walk} minutes on foot. Moscow time.`,
    tags: [row.category, row.studio, station?.name ?? 'Online'].filter(Boolean),
    goals: row.goals,
    popularityScore: row.pop,
    featured: row.featured,
    newActivity: row.fresh ?? false,
    rating: 0,
    reviewCount: 0,
    delivery: row.delivery ?? 'In Person',
    meetingPlatform: row.platform,
    bookingKind:
      row.booking ?? (row.template === 'Corporate' ? 'Request Spot' : 'Instant Booking'),
    capacity: seats,
    availableSeats: Math.max(row.audience === 'Corporate' ? seats : 1, seats - taken),
    studioName: row.studio,
    teacherName: row.host,
    teacherBio: row.bio,
    coverImage: coverFor(row.category, row.cover ?? index),
    cancellationPolicy: 'Free cancellation up to 24 hours before the session.',
    responseTimeText: 'usually within 2 hours',
  };
}

export function buildCatalog(): Activity[] {
  return REAL.map((row, i) => toActivity(row, i));
}

export function extraPhotos(activity: Activity): string[] {
  const pool = [...new Set(COVER[activity.category] ?? COVER['Yoga'] ?? [])];
  const start = Math.max(0, pool.indexOf(activity.coverImage));
  const extras: string[] = [];
  for (let i = 1; i <= pool.length && extras.length < 3; i++) {
    const url = pool[(start + i) % pool.length];
    if (url && url !== activity.coverImage && !extras.includes(url)) extras.push(url);
  }
  if (extras.length < 3) {
    for (const url of COVER['Yoga'] ?? []) {
      if (url !== activity.coverImage && !extras.includes(url)) extras.push(url);
      if (extras.length === 3) break;
    }
  }
  return extras;
}

export function listingPhotos(activity: Activity): string[] {
  return [activity.coverImage, ...extraPhotos(activity)].filter(
    (url, i, all) => Boolean(url) && all.indexOf(url) === i,
  );
}

export function assertCatalog(list: Activity[]): void {
  if (list.length < 30) throw new Error(`Catalog too small: ${list.length}`);
  const ids = new Set(list.map((a) => a.id));
  if (ids.size !== list.length) throw new Error('Duplicate activity ids');
}
